services:
  app:
    command: 
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./internal:/app/internal
      - ./cmd:/app/cmd
      - ./graph:/app/graph
      - ./protobuf:/app/protobuf
      - ./pkg:/app/pkg
    env_file:
        - .env