package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"

	"github.com/hhertout/graphql_api_boilerplate/graph"
	"github.com/hhertout/graphql_api_boilerplate/internal/application/dtos"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input dtos.NewTodo) (*dtos.Todo, error) {
	return &dtos.Todo{
		ID:   "1",
		Text: "Hello world",
		Done: false,
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*dtos.Todo, error) {
	todo := dtos.Todo{
		ID:   "1",
		Text: "Hello world",
		Done: false,
	}

	return []*dtos.Todo{&todo}, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
